-- MySQL Script generated by MySQL Workbench
-- Mon Sep 26 17:44:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`regions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`regions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`divisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`divisions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`divisions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tiers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tiers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tiers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ranks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ranks` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ranks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lp` INT NULL,
  `divisions_id` INT NOT NULL,
  `tiers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ranks_divisions1_idx` (`divisions_id` ASC) VISIBLE,
  INDEX `fk_ranks_tiers1_idx` (`tiers_id` ASC) VISIBLE,
  CONSTRAINT `fk_ranks_divisions1`
    FOREIGN KEY (`divisions_id`)
    REFERENCES `mydb`.`divisions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ranks_tiers1`
    FOREIGN KEY (`tiers_id`)
    REFERENCES `mydb`.`tiers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`summoners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`summoners` ;

CREATE TABLE IF NOT EXISTS `mydb`.`summoners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `level` INT NULL,
  `icon` INT NULL,
  `regions_id` INT NOT NULL,
  `ranks_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ranks_id`),
  INDEX `fk_summoners_regions1_idx` (`regions_id` ASC) VISIBLE,
  INDEX `fk_summoners_ranks1_idx` (`ranks_id` ASC) VISIBLE,
  CONSTRAINT `fk_summoners_regions1`
    FOREIGN KEY (`regions_id`)
    REFERENCES `mydb`.`regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_summoners_ranks1`
    FOREIGN KEY (`ranks_id`)
    REFERENCES `mydb`.`ranks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gamemodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gamemodes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`gamemodes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`matches` ;

CREATE TABLE IF NOT EXISTS `mydb`.`matches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `duration` INT NULL,
  `gamemodes_id` INT NOT NULL,
  `game_creation` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_matches_gamemodes_idx` (`gamemodes_id` ASC) VISIBLE,
  CONSTRAINT `fk_matches_gamemodes`
    FOREIGN KEY (`gamemodes_id`)
    REFERENCES `mydb`.`gamemodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teams` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matchWon` TINYINT(1) NULL,
  `matches_id` INT NOT NULL,
  PRIMARY KEY (`id`, `matches_id`),
  INDEX `fk_teams_matches1_idx` (`matches_id` ASC) VISIBLE,
  CONSTRAINT `fk_teams_matches1`
    FOREIGN KEY (`matches_id`)
    REFERENCES `mydb`.`matches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`positions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`positions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`champions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`champions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`champions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`participants` ;

CREATE TABLE IF NOT EXISTS `mydb`.`participants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assists` INT NULL,
  `deaths` INT NULL,
  `kills` INT NULL,
  `baronkills` INT NULL,
  `consumablePurchased` INT NULL,
  `damageDealtToBuildings` INT NULL,
  `damageDealtToObjectives` INT NULL,
  `damageDealtToTurrets` INT NULL,
  `damageSelfMitigated` INT NULL,
  `doubleKills` INT NULL,
  `tripleKills` INT NULL,
  `quadraKills` INT NULL,
  `pentaKills` INT NULL,
  `teams_id` INT NOT NULL,
  `summoners_id` INT NOT NULL,
  `positions_id` INT NOT NULL,
  `champions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `teams_id`),
  INDEX `fk_participants_teams1_idx` (`teams_id` ASC) VISIBLE,
  INDEX `fk_participants_summoners1_idx` (`summoners_id` ASC) VISIBLE,
  INDEX `fk_participants_positions1_idx` (`positions_id` ASC) VISIBLE,
  INDEX `fk_participants_champions1_idx` (`champions_id` ASC) VISIBLE,
  CONSTRAINT `fk_participants_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participants_summoners1`
    FOREIGN KEY (`summoners_id`)
    REFERENCES `mydb`.`summoners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participants_positions1`
    FOREIGN KEY (`positions_id`)
    REFERENCES `mydb`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participants_champions1`
    FOREIGN KEY (`champions_id`)
    REFERENCES `mydb`.`champions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`masteries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`masteries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`masteries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level` INT NULL,
  `championsPoints` INT NULL,
  `lastPlayed` DATETIME NULL,
  `summoners_id` INT NOT NULL,
  `summoners_ranks_id` INT NOT NULL,
  `champions_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_masteries_summoners1_idx` (`summoners_id` ASC, `summoners_ranks_id` ASC) VISIBLE,
  INDEX `fk_masteries_champions1_idx` (`champions_id` ASC) VISIBLE,
  CONSTRAINT `fk_masteries_summoners1`
    FOREIGN KEY (`summoners_id` , `summoners_ranks_id`)
    REFERENCES `mydb`.`summoners` (`id` , `ranks_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_masteries_champions1`
    FOREIGN KEY (`champions_id`)
    REFERENCES `mydb`.`champions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teams_bans_champions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teams_bans_champions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teams_bans_champions` (
  `teams_id` INT NOT NULL,
  `teams_matches_id` INT NOT NULL,
  `champions_id` INT NOT NULL,
  PRIMARY KEY (`teams_id`, `teams_matches_id`, `champions_id`),
  INDEX `fk_teams_has_champions_champions1_idx` (`champions_id` ASC) VISIBLE,
  INDEX `fk_teams_has_champions_teams1_idx` (`teams_id` ASC, `teams_matches_id` ASC) VISIBLE,
  CONSTRAINT `fk_teams_has_champions_teams1`
    FOREIGN KEY (`teams_id` , `teams_matches_id`)
    REFERENCES `mydb`.`teams` (`id` , `matches_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teams_has_champions_champions1`
    FOREIGN KEY (`champions_id`)
    REFERENCES `mydb`.`champions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS audit_matches;

CREATE TABLE audit_matches(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    matches_played INT NOT NULL,
    day VARCHAR(15) NOT NULL
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
